"""Colour schemes for chemical classifications."""

PALETTES = {
    "default": {
        "alkali-metal": "#EE8866",
        "alkaline-earth-metal": "#EEDD88",
        "transition-metal": "#77AADD",
        "post-transition-metal": "#99DDFF",
        "metalloid": "#44BB99",
        "reactive-nonmetal": "#BBCC33",
        "halogen": "#AAAA00",
        "noble-gas": "#DDDDDD",
        "lanthanide": "#DDBBDD",
        "actinide": "#FFAABB",
        "unknown-chemistry": "#F4F4F4",
    },
    "classic": {
        "alkali-metal": "#F3C363",
        "alkaline-earth-metal": "#F5E77A",
        "transition-metal": "#8EC9E6",
        "post-transition-metal": "#79ACD2",
        "metalloid": "#75C7AC",
        "reactive-nonmetal": "#E4A7C9",
        "halogen": "#E89A75",
        "noble-gas": "#B5A0D0",
        "lanthanide": "#A5DDEB",
        "actinide": "#D59AC8",
        "unknown-chemistry": "#FAFAFA",
    },
    "light": {
        "alkali-metal": "#F8DFA4",
        "alkaline-earth-metal": "#F8F0AE",
        "transition-metal": "#B8DDF0",
        "post-transition-metal": "#A7CDE5",
        "metalloid": "#A8DCCB",
        "reactive-nonmetal": "#EFC9DF",
        "halogen": "#F2B79D",
        "noble-gas": "#D0C2E3",
        "lanthanide": "#C6E8F0",
        "actinide": "#E4BEDD",
        "unknown-chemistry": "#FAFAFA",
    },
    "vibrant": {
        "alkali-metal": "#F4B942",
        "alkaline-earth-metal": "#F2DE4F",
        "transition-metal": "#55B8E6",
        "post-transition-metal": "#4D91C6",
        "metalloid": "#4DBE9D",
        "reactive-nonmetal": "#E889BE",
        "halogen": "#EB7952",
        "noble-gas": "#9D82C4",
        "lanthanide": "#78CFE3",
        "actinide": "#CA79B8",
        "unknown-chemistry": "#FAFAFA",
    },
    "soft-cool": {
        "alkali-metal": "#F2D49B",
        "alkaline-earth-metal": "#EEE7A7",
        "transition-metal": "#A9D3E1",
        "post-transition-metal": "#8DB9D1",
        "metalloid": "#9BCDBB",
        "reactive-nonmetal": "#DDB6CF",
        "halogen": "#DFA58D",
        "noble-gas": "#BDAFD2",
        "lanthanide": "#B9DFE5",
        "actinide": "#CEAAC8",
        "unknown-chemistry": "#FAFAFA",
    },
    "powder": {
        "alkali-metal": "#F6D2AB",
        "alkaline-earth-metal": "#FDF7B3",
        "transition-metal": "#DFD5D8",
        "post-transition-metal": "#EDE0CD",
        "metalloid": "#F1FEF5",
        "reactive-nonmetal": "#C3DBFE",
        "halogen": "#FEFDD3",
        "noble-gas": "#BDBED6",
        "lanthanide": "#F5EBFF",
        "actinide": "#D7BAB1",
        "unknown-chemistry": "#E6E9EA",
    },
    "print": {
        "alkali-metal": "#FFFFFF",
        "alkaline-earth-metal": "#F5F5F5",
        "transition-metal": "#D8D8D8",
        "post-transition-metal": "#E3E3E3",
        "metalloid": "#EEEEEE",
        "reactive-nonmetal": "#CCCCCC",
        "halogen": "#F9F9F9",
        "noble-gas": "#BEBEBE",
        "lanthanide": "#E9E9E9",
        "actinide": "#C6C6C6",
        "unknown-chemistry": "#F2F2F2",
    },
    "mineral": {
        "alkali-metal": "#EBC8A0",
        "alkaline-earth-metal": "#E8DC9A",
        "transition-metal": "#B8CED0",
        "post-transition-metal": "#C8B8A3",
        "metalloid": "#B8D2BE",
        "reactive-nonmetal": "#C8C1D8",
        "halogen": "#DDAF8D",
        "noble-gas": "#AEB8CD",
        "lanthanide": "#C9D8C2",
        "actinide": "#CCAFA4",
        "unknown-chemistry": "#E4E2DC",
    },
    "nordic": {
        "alkali-metal": "#E8D7B7",
        "alkaline-earth-metal": "#EEE6BE",
        "transition-metal": "#BED5DF",
        "post-transition-metal": "#B4C7D2",
        "metalloid": "#C2DACF",
        "reactive-nonmetal": "#D4D1E2",
        "halogen": "#E5C5B7",
        "noble-gas": "#B9BED3",
        "lanthanide": "#D1E1DF",
        "actinide": "#D5BEC2",
        "unknown-chemistry": "#E8EBEC",
    },
    "high-contrast-pastel": {
        "alkali-metal": "#FFD0A3",
        "alkaline-earth-metal": "#FFF2A6",
        "transition-metal": "#A8D8EE",
        "post-transition-metal": "#B8C5E2",
        "metalloid": "#A9DEC4",
        "reactive-nonmetal": "#F1B9D8",
        "halogen": "#FFC0A8",
        "noble-gas": "#C3B1E1",
        "lanthanide": "#BDE8E8",
        "actinide": "#E4B5CC",
        "unknown-chemistry": "#F4F4F4",
    },
    "blue-ramp": {
        "alkali-metal": "#5B9BD5",
        "alkaline-earth-metal": "#A8CBEB",
        "transition-metal": "#C6DCF0",
        "post-transition-metal": "#F2F7FC",
        "metalloid": "#8FC47A",
        "reactive-nonmetal": "#F9CCCC",
        "halogen": "#E06666",
        "noble-gas": "#D7B3EC",
        "lanthanide": "#B3C1D8",
        "actinide": "#8B9CBB",
        "unknown-chemistry": "#E8EBEC",
    },
    "tol-light-inspired": {
        "alkali-metal": "#EE8866",
        "alkaline-earth-metal": "#EEDD88",
        "transition-metal": "#77AADD",
        "post-transition-metal": "#99DDFF",
        "metalloid": "#44BB99",
        "reactive-nonmetal": "#BBCC33",
        "halogen": "#AAAA00",
        "noble-gas": "#DDDDDD",
        "lanthanide": "#DDBBDD",
        "actinide": "#FFAABB",
        "unknown-chemistry": "#F4F4F4",
    },
    "tol-muted-inspired": {
        "alkali-metal": "#DE9BA7",
        "alkaline-earth-metal": "#E9DFA6",
        "transition-metal": "#B2DDF4",
        "post-transition-metal": "#DDDDDD",
        "metalloid": "#64A576",
        "reactive-nonmetal": "#85C7BC",
        "halogen": "#B97090",
        "noble-gas": "#8178B6",
        "lanthanide": "#C47FB8",
        "actinide": "#BFBF7A",
        "unknown-chemistry": "#F4F4F4",
    },
    "broad-light": {
        "alkali-metal": "#A8CBEB",
        "alkaline-earth-metal": "#A8CBEB",
        "transition-metal": "#A8CBEB",
        "post-transition-metal": "#A8CBEB",
        "metalloid": "#8FC47A",
        "reactive-nonmetal": "#F9CCCC",
        "halogen": "#F9CCCC",
        "noble-gas": "#D7B3EC",
        "lanthanide": "#A8CBEB",
        "actinide": "#A8CBEB",
        "unknown-chemistry": "#E8EBEC",
    },
    "broad-tol-light": {
        "alkali-metal": "#77AADD",
        "alkaline-earth-metal": "#77AADD",
        "transition-metal": "#77AADD",
        "post-transition-metal": "#77AADD",
        "metalloid": "#44BB99",
        "reactive-nonmetal": "#EE8866",
        "halogen": "#EE8866",
        "noble-gas": "#FFAABB",
        "lanthanide": "#77AADD",
        "actinide": "#77AADD",
        "unknown-chemistry": "#DDDDDD",
    },
}

PALETTE_THEMES = {
    name: {
        "page": "#FFFFFF",
        "text": "#111111",
        "source": "#666666",
        "rule": "#222222",
        "guide": "#555555",
        "placeholder": "#F2F2F2",
    }
    for name in PALETTES
}
SUPPORTED_COLOUR_SCHEMES = tuple(PALETTES)


def get_palette(name: str) -> dict[str, str]:
    """Return a named palette or reject an unsupported name."""
    try:
        return PALETTES[name]
    except KeyError as error:
        choices = ", ".join(SUPPORTED_COLOUR_SCHEMES)
        raise ValueError(
            f"Unsupported colour scheme: {name!r}; choose {choices}"
        ) from error


def get_palette_theme(name: str) -> dict[str, str]:
    """Return page, text, and rule colours for a named palette."""
    get_palette(name)
    return PALETTE_THEMES[name]
